{% set version = "3.0" %}
{% set build = 0 %}

package:
  name: miniforge_console_shortcut
  version: {{ version }}

build:
  number: {{ build }}
  skip: True  # [not win]

requirements:
  run:
    - menuinst >=2.3.1
test:
  commands:
    - if not exist %PREFIX%\\Menu\\console_shortcut_menu.json exit 1 # [win]
    - if not exist %PREFIX%\\Menu\\console_shortcut.ico exit 1       # [win]
    - dir %PREFIX%\\Menu                                             # [win]

about:
  home: https://github.com/conda-forge/miniforge_console_shortcut-feedstock
  summary: Command prompt shortcut for Windows with base environment activated
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ericpre
